--------------------------------------------------------------------------------
-- PROJECT C — APPROVAL DOMAIN (ORACLE / APEX DEMO)
--
-- Core idea:
--   We store EVENTS only.
--   We derive:
--     - state
--     - available actions
--
--   history → state → actions → user → event → history
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 1. EVENTS TABLE
--------------------------------------------------------------------------------

CREATE TABLE approval_events (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id     VARCHAR2(100),
    event_type    VARCHAR2(50),

    participant   VARCHAR2(100),

    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------------------------------------
-- EVENT TYPES:
--   PROPOSED      (participants defined separately)
--   ADD_PARTICIPANT
--   APPROVED
--   REJECTED
--   EXPIRED
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 2. DERIVED STATE VIEW
--------------------------------------------------------------------------------
-- This reconstructs the current truth.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW approval_state_v AS
WITH

participants AS (
    SELECT stream_id, participant
    FROM approval_events
    WHERE event_type = 'ADD_PARTICIPANT'
),

approved AS (
    SELECT stream_id, participant
    FROM approval_events
    WHERE event_type = 'APPROVED'
),

rejected AS (
    SELECT stream_id, participant
    FROM approval_events
    WHERE event_type = 'REJECTED'
),

expired AS (
    SELECT DISTINCT stream_id
    FROM approval_events
    WHERE event_type = 'EXPIRED'
)

SELECT
    p.stream_id,
    p.participant,

    CASE
        WHEN a.participant IS NOT NULL THEN 'APPROVED'
        WHEN r.participant IS NOT NULL THEN 'REJECTED'
        ELSE 'PENDING'
    END AS participant_status,

    -- Global state flags
    CASE
        WHEN EXISTS (
            SELECT 1 FROM rejected r2
            WHERE r2.stream_id = p.stream_id
        )
        THEN 'REJECTED'
        WHEN NOT EXISTS (
            SELECT 1
            FROM participants p2
            WHERE p2.stream_id = p.stream_id
              AND NOT EXISTS (
                  SELECT 1 FROM approved a2
                  WHERE a2.stream_id = p2.stream_id
                    AND a2.participant = p2.participant
              )
        )
        THEN 'APPROVED'
        WHEN EXISTS (
            SELECT 1 FROM expired e
            WHERE e.stream_id = p.stream_id
        )
        THEN 'EXPIRED'
        ELSE 'PENDING'
    END AS overall_status

FROM participants p
LEFT JOIN approved a
    ON a.stream_id = p.stream_id
   AND a.participant = p.participant
LEFT JOIN rejected r
    ON r.stream_id = p.stream_id
   AND r.participant = p.participant;

--------------------------------------------------------------------------------
-- Interpretation:
--
-- participant_status:
--   APPROVED / REJECTED / PENDING
--
-- overall_status:
--   REJECTED → any reject
--   APPROVED → all approved
--   EXPIRED  → explicitly expired
--   PENDING  → otherwise
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 3. AVAILABLE ACTIONS VIEW
--------------------------------------------------------------------------------
-- This derives VALID actions (core idea).
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW approval_actions_v AS
SELECT
    stream_id,
    participant,
    'approve ' || participant AS action_label
FROM approval_state_v
WHERE participant_status = 'PENDING'
  AND overall_status = 'PENDING'

UNION ALL

SELECT
    stream_id,
    participant,
    'reject ' || participant AS action_label
FROM approval_state_v
WHERE participant_status = 'PENDING'
  AND overall_status = 'PENDING'

UNION ALL

SELECT DISTINCT
    stream_id,
    NULL AS participant,
    'expire' AS action_label
FROM approval_state_v
WHERE overall_status = 'PENDING';

--------------------------------------------------------------------------------
-- Key idea:
--   Only valid actions appear.
--
-- No need to:
--   "try → reject"
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 4. WRITE PROCEDURES (ENFORCEMENT)
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE approve_participant (
    p_stream_id IN VARCHAR2,
    p_participant IN VARCHAR2
) AS
    v_count NUMBER;
BEGIN

    -- must exist
    SELECT COUNT(*) INTO v_count
    FROM approval_state_v
    WHERE stream_id = p_stream_id
      AND participant = p_participant;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Unknown participant');
    END IF;

    -- must be pending
    SELECT COUNT(*) INTO v_count
    FROM approval_state_v
    WHERE stream_id = p_stream_id
      AND participant = p_participant
      AND participant_status <> 'PENDING';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Already acted');
    END IF;

    -- must not be terminal
    SELECT COUNT(*) INTO v_count
    FROM approval_state_v
    WHERE stream_id = p_stream_id
      AND overall_status <> 'PENDING';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Already terminal');
    END IF;

    INSERT INTO approval_events (stream_id, event_type, participant)
    VALUES (p_stream_id, 'APPROVED', p_participant);

END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE reject_participant (
    p_stream_id IN VARCHAR2,
    p_participant IN VARCHAR2
) AS
BEGIN
    INSERT INTO approval_events (stream_id, event_type, participant)
    VALUES (p_stream_id, 'REJECTED', p_participant);
END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE expire_approval (
    p_stream_id IN VARCHAR2
) AS
BEGIN
    INSERT INTO approval_events (stream_id, event_type)
    VALUES (p_stream_id, 'EXPIRED');
END;
/

--------------------------------------------------------------------------------
-- Note:
-- We still enforce rules via state view checks (like in approve).
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 5. DEMO DATA
--------------------------------------------------------------------------------

INSERT INTO approval_events (stream_id, event_type, participant)
VALUES ('demo', 'ADD_PARTICIPANT', 'Alice');

INSERT INTO approval_events (stream_id, event_type, participant)
VALUES ('demo', 'ADD_PARTICIPANT', 'Bob');

COMMIT;

--------------------------------------------------------------------------------
-- 6. APEX USAGE
--------------------------------------------------------------------------------

-- State:
--   SELECT * FROM approval_state_v WHERE stream_id = :P1_ID;

-- Actions:
--   SELECT * FROM approval_actions_v WHERE stream_id = :P1_ID;

-- Buttons:
--   approve_participant(...)
--   reject_participant(...)
--   expire_approval(...)

--------------------------------------------------------------------------------
-- RESULT:
--
-- Initial:
--   approve Alice
--   approve Bob
--   reject Alice
--   reject Bob
--   expire
--
-- After Alice approves:
--   approve Bob
--   reject Bob
--   expire
--
-- After Bob rejects:
--   (no actions)
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- FINAL TAKEAWAY
--------------------------------------------------------------------------------
-- Same structure as tasks:
--
--   events → state view → actions view → write procedures
--
-- Different domain, same architecture.
--------------------------------------------------------------------------------
