--------------------------------------------------------------------------------
-- PROJECT C — ORDER LIFECYCLE DOMAIN
--
-- Demonstrates:
--   ✔ sequential transitions
--   ✔ conditional actions
--   ✔ irreversible states
--
-- Pattern:
--   events → state view → actions view → write procedures
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 1. EVENTS TABLE
--------------------------------------------------------------------------------

CREATE TABLE order_events (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id     VARCHAR2(100),
    event_type    VARCHAR2(50),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------------------------------------
-- EVENT TYPES:
--   CREATED
--   PAID
--   SHIPPED
--   DELIVERED
--   CANCELLED
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 2. STATE VIEW
--------------------------------------------------------------------------------
-- Derives current order status from history
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW order_state_v AS
SELECT
    stream_id,

    CASE
        WHEN MAX(CASE WHEN event_type = 'CANCELLED' THEN 1 END) = 1
            THEN 'CANCELLED'

        WHEN MAX(CASE WHEN event_type = 'DELIVERED' THEN 1 END) = 1
            THEN 'DELIVERED'

        WHEN MAX(CASE WHEN event_type = 'SHIPPED' THEN 1 END) = 1
            THEN 'SHIPPED'

        WHEN MAX(CASE WHEN event_type = 'PAID' THEN 1 END) = 1
            THEN 'PAID'

        WHEN MAX(CASE WHEN event_type = 'CREATED' THEN 1 END) = 1
            THEN 'NEW'

        ELSE 'UNKNOWN'
    END AS status

FROM order_events
GROUP BY stream_id;

--------------------------------------------------------------------------------
-- Note:
-- Highest-priority event determines state
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 3. ACTIONS VIEW
--------------------------------------------------------------------------------
-- Only valid actions are exposed
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW order_actions_v AS

SELECT stream_id, 'pay' AS action
FROM order_state_v
WHERE status = 'NEW'

UNION ALL

SELECT stream_id, 'cancel'
FROM order_state_v
WHERE status IN ('NEW', 'PAID')

UNION ALL

SELECT stream_id, 'ship'
FROM order_state_v
WHERE status = 'PAID'

UNION ALL

SELECT stream_id, 'deliver'
FROM order_state_v
WHERE status = 'SHIPPED';

--------------------------------------------------------------------------------
-- Key idea:
--   UI never sees invalid actions
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 4. WRITE PROCEDURES
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE order_pay (
    p_stream_id IN VARCHAR2
) AS
    v_status VARCHAR2(50);
BEGIN

    SELECT status INTO v_status
    FROM order_state_v
    WHERE stream_id = p_stream_id;

    IF v_status <> 'NEW' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cannot pay in this state');
    END IF;

    INSERT INTO order_events (stream_id, event_type)
    VALUES (p_stream_id, 'PAID');

END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE order_ship (
    p_stream_id IN VARCHAR2
) AS
    v_status VARCHAR2(50);
BEGIN

    SELECT status INTO v_status
    FROM order_state_v
    WHERE stream_id = p_stream_id;

    IF v_status <> 'PAID' THEN
        RAISE_APPLICATION_ERROR(-20002, 'Cannot ship');
    END IF;

    INSERT INTO order_events (stream_id, event_type)
    VALUES (p_stream_id, 'SHIPPED');

END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE order_deliver (
    p_stream_id IN VARCHAR2
) AS
BEGIN
    INSERT INTO order_events (stream_id, event_type)
    VALUES (p_stream_id, 'DELIVERED');
END;
/

--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE order_cancel (
    p_stream_id IN VARCHAR2
) AS
    v_status VARCHAR2(50);
BEGIN

    SELECT status INTO v_status
    FROM order_state_v
    WHERE stream_id = p_stream_id;

    IF v_status NOT IN ('NEW', 'PAID') THEN
        RAISE_APPLICATION_ERROR(-20003, 'Cannot cancel');
    END IF;

    INSERT INTO order_events (stream_id, event_type)
    VALUES (p_stream_id, 'CANCELLED');

END;
/

--------------------------------------------------------------------------------
-- Again:
--   no updates → only append events
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 5. DEMO DATA
--------------------------------------------------------------------------------

INSERT INTO order_events (stream_id, event_type)
VALUES ('order1', 'CREATED');

COMMIT;

--------------------------------------------------------------------------------
-- 6. APEX USAGE
--------------------------------------------------------------------------------

-- State:
--   SELECT * FROM order_state_v WHERE stream_id = :P1_ID;

-- Actions:
--   SELECT * FROM order_actions_v WHERE stream_id = :P1_ID;

-- Buttons:
--   order_pay(...)
--   order_ship(...)
--   order_deliver(...)
--   order_cancel(...)

--------------------------------------------------------------------------------
-- Example flow:
--
-- NEW → pay → PAID → ship → SHIPPED → deliver → DELIVERED
--
-- Cancel disappears after shipping.
--------------------------------------------------------------------------------
