--------------------------------------------------------------------------------
-- PROJECT C — TASK DEPENDENCY MODEL (ORACLE / APEX DEMO)
--
-- Core idea:
--   We NEVER store mutable state.
--   We store EVENTS, and derive everything else.
--
--   history → state → available actions → user chooses → new event
--
-- This file demonstrates:
--   ✔ Event sourcing (event table)
--   ✔ State derivation (views)
--   ✔ Action derivation (views)
--   ✔ Enforcement via PL/SQL (no invalid writes)
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
-- 1. EVENTS TABLE (THE ONLY SOURCE OF TRUTH)
--------------------------------------------------------------------------------

-- Each row is an immutable fact.
-- No updates. No deletes (in real systems).

CREATE TABLE task_events (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id     VARCHAR2(100),
    event_type    VARCHAR2(50),

    -- payload
    task_name     VARCHAR2(100),
    depends_on    VARCHAR2(100),

    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--------------------------------------------------------------------------------
-- EVENT TYPES:
--   DEFINE_TASK       (task_name)
--   ADD_DEPENDENCY    (task_name depends_on)
--   COMPLETE_TASK     (task_name)
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 2. DERIVED STATE VIEW
--------------------------------------------------------------------------------
-- This view reconstructs current state from events.
-- This is your "Projector" in SQL form.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW task_state_v AS
WITH

-- All defined tasks
tasks AS (
    SELECT DISTINCT stream_id, task_name
    FROM task_events
    WHERE event_type = 'DEFINE_TASK'
),

-- Dependency edges
deps AS (
    SELECT stream_id, task_name, depends_on
    FROM task_events
    WHERE event_type = 'ADD_DEPENDENCY'
),

-- Completed tasks
completed AS (
    SELECT stream_id, task_name
    FROM task_events
    WHERE event_type = 'COMPLETE_TASK'
)

SELECT
    t.stream_id,
    t.task_name,

    CASE
        WHEN c.task_name IS NOT NULL THEN 'DONE'
        ELSE 'PENDING'
    END AS status,

    -- Is task blocked?
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM deps d
            WHERE d.stream_id = t.stream_id
              AND d.task_name = t.task_name
              AND NOT EXISTS (
                  SELECT 1
                  FROM completed c2
                  WHERE c2.stream_id = t.stream_id
                    AND c2.task_name = d.depends_on
              )
        )
        THEN 'BLOCKED'
        ELSE 'UNBLOCKED'
    END AS block_status

FROM tasks t
LEFT JOIN completed c
    ON c.stream_id = t.stream_id
   AND c.task_name = t.task_name;

--------------------------------------------------------------------------------
-- Interpretation:
--   - DONE: already completed
--   - PENDING + BLOCKED: cannot act yet
--   - PENDING + UNBLOCKED: valid next action
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 3. AVAILABLE ACTIONS VIEW
--------------------------------------------------------------------------------
-- This is the key idea:
--   Instead of validating actions later,
--   we ONLY expose VALID actions.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW task_actions_v AS
SELECT
    stream_id,
    task_name,
    'complete ' || task_name AS action_label
FROM task_state_v
WHERE status = 'PENDING'
  AND block_status = 'UNBLOCKED';

--------------------------------------------------------------------------------
-- This replaces traditional validation.
--
-- Instead of:
--   "try action → reject if invalid"
--
-- We do:
--   "only show valid actions"
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 4. WRITE FUNCTION (ENFORCEMENT)
--------------------------------------------------------------------------------
-- Even though UI shows valid actions,
-- we STILL enforce correctness at write time.
--
-- This ensures:
--   ✔ safety
--   ✔ no invalid states even if bypassing UI
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE complete_task (
    p_stream_id IN VARCHAR2,
    p_task      IN VARCHAR2
) AS
    v_count NUMBER;
BEGIN

    ------------------------------------------------------------------------
    -- Check task exists
    ------------------------------------------------------------------------
    SELECT COUNT(*)
    INTO v_count
    FROM task_state_v
    WHERE stream_id = p_stream_id
      AND task_name = p_task;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Unknown task');
    END IF;

    ------------------------------------------------------------------------
    -- Check not already completed
    ------------------------------------------------------------------------
    SELECT COUNT(*)
    INTO v_count
    FROM task_state_v
    WHERE stream_id = p_stream_id
      AND task_name = p_task
      AND status = 'DONE';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Already completed');
    END IF;

    ------------------------------------------------------------------------
    -- Check not blocked
    ------------------------------------------------------------------------
    SELECT COUNT(*)
    INTO v_count
    FROM task_state_v
    WHERE stream_id = p_stream_id
      AND task_name = p_task
      AND block_status = 'BLOCKED';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Task is blocked');
    END IF;

    ------------------------------------------------------------------------
    -- If all checks pass → append event
    ------------------------------------------------------------------------
    INSERT INTO task_events (stream_id, event_type, task_name)
    VALUES (p_stream_id, 'COMPLETE_TASK', p_task);

END;
/

--------------------------------------------------------------------------------
-- Important:
--   We DO NOT update state.
--   We append an event.
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- 5. DEMO DATA
--------------------------------------------------------------------------------

-- Define tasks
INSERT INTO task_events (stream_id, event_type, task_name)
VALUES ('demo', 'DEFINE_TASK', 'A');

INSERT INTO task_events (stream_id, event_type, task_name)
VALUES ('demo', 'DEFINE_TASK', 'B');

INSERT INTO task_events (stream_id, event_type, task_name)
VALUES ('demo', 'DEFINE_TASK', 'C');

-- Add dependencies
INSERT INTO task_events (stream_id, event_type, task_name, depends_on)
VALUES ('demo', 'ADD_DEPENDENCY', 'C', 'A');

INSERT INTO task_events (stream_id, event_type, task_name, depends_on)
VALUES ('demo', 'ADD_DEPENDENCY', 'C', 'B');

COMMIT;

--------------------------------------------------------------------------------
-- 6. HOW TO USE IN APEX
--------------------------------------------------------------------------------

-- Region 1: Current State
--   SELECT * FROM task_state_v WHERE stream_id = :P1_STREAM_ID;

-- Region 2: Available Actions
--   SELECT * FROM task_actions_v WHERE stream_id = :P1_STREAM_ID;

-- Button:
--   call complete_task(:P1_STREAM_ID, :P1_TASK);

--------------------------------------------------------------------------------
-- Result:
--
-- Initial:
--   complete A
--   complete B
--
-- After A:
--   complete B
--
-- After A + B:
--   complete C
--
-- No invalid actions ever appear.
--------------------------------------------------------------------------------



--------------------------------------------------------------------------------
-- FINAL TAKEAWAY
--------------------------------------------------------------------------------
-- This system does NOT:
--   ✘ validate user input after the fact
--
-- It DOES:
--   ✔ derive valid actions from state
--   ✔ enforce correctness via replay logic
--
-- This is "correctness by construction"
--------------------------------------------------------------------------------
